#!/bin/sh
mvn -q -e exec:java -Dexec.mainClass=net.sf.juoserver.protocol.Packets -Dexec.args="$*"
RESULT=$?
if [ "x$RESULT" != "x0" ]; then
    echo "Examples:"
    echo "\t Decompresses the hex number sequence '0x76 and 0x34':"
    echo "\t\t./packets d \'0x76, 0x34\'"
    echo "\t The same, but without spaces between numbers:"
    echo "\t\t./packets d 0x76,0x34"
    echo "\t The same, but without spaces nor '0x' or commas:"
    echo "\t\t./packets d 7634"
    echo "\t Decompresses the same two numbers as before, but using a pipe:"
    echo "\t\techo 0x76, 0x34 | ./packets d"
    echo "\t Same as before, but discarding debug messages (useful for more pipes):"
    echo "\t\techo 0x76, 0x34 | ./packets d 2> /dev/null"
    echo "\t Decompresses whatever the user provides from the command line:"
    echo "\t\t./packets d"
    echo "\t Decompresses the whole content of file 'src/site/resources/testpacket':"
    echo "\t\tcat src/site/resources/testpacket | ./packets d"
    echo "\t Same as before, but discarding debug messages:"
    echo "\t\tcat src/site/resources/testpacket | ./packets d 2> /dev/null"
    echo "\t Translates the hex numbers 0x77, 0x61 and 0x72 into a string ('war'):"
    echo "\t\t./packets h 776172"
    echo "\t Does the same, but using the unicode encoding (each char is made of two bytes and the first is '00'):"
    echo "\t\t./packets u 007700610072"
fi

exit $RESULT

